// hide_summary.go — the hide-time auto-summariser. When the model
// calls context:hide, the runtime distils the segment's raw entries
// into a ≤~500-token brief that becomes the placeholder, so a hide
// never silently drops a standing instruction the agent read mid-task
// (the dogfood failure: a researcher hid the "validate every query"
// rule it had read and then wrote invalid queries). The brief is
// generated by a CHEAP, dedicated summarise call — not left to the
// (weak) worker model to self-summarise — and is seeded by the agent's
// own optional `note`.
package compactor

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/hugr-lab/hugen/pkg/extension"
	"github.com/hugr-lab/hugen/pkg/model"
)

const (
	// hideBriefMaxTokens caps the generated placeholder brief.
	hideBriefMaxTokens = 500
	// hideBriefEntryMaxChars clips any single oversized entry (a big
	// data dump) before it dominates the input budget. Aligned with the
	// L1 read cap (bash-mcp's read_context_max_bytes, 16000) so a full
	// file-read result — the usual carrier of the standing instructions
	// we must NOT lose — is never clipped tighter than the read that
	// produced it. Only larger entries (big query result dumps, where
	// the shape matters more than the bulk) get trimmed.
	hideBriefEntryMaxChars = 16000
	// hideBriefWindowFactor scales the input budget off the checkpoint
	// window: a segment is the window plus the overshoot of the tool
	// round that blew it, so window × 1.2 holds a typical segment whole.
	// Applied as ×12/10 over CheckpointWindowTokens.
	hideBriefWindowFactorNum = 12
	hideBriefWindowFactorDen = 10
)

// SegmentSummarizer distils a checkpoint-segment into the placeholder
// brief shown after context:hide. Implemented by [*Extension] (which
// owns the model router + the per-tier config resolver); the
// [ContextProvider] holds one so its hide handler can produce the
// brief. Exported so the runtime can wire the compactor extension in as
// the summariser and tests can stub it. state supplies the renderer
// (state.Prompts) and resolves the per-tier checkpoint window that
// sizes the input budget.
type SegmentSummarizer interface {
	SummarizeSegment(ctx context.Context, state extension.SessionState, entries []HistoryEntry, agentNote string) (string, error)
}

var _ SegmentSummarizer = (*Extension)(nil)

// hideBriefInput binds `assets/prompts/compactor/hide_brief.tmpl`.
type hideBriefInput struct {
	AgentNote string
	RawLog    string
	MaxTokens int
}

// SummarizeSegment implements [SegmentSummarizer]. Resolves the cheap
// summarise intent (the router falls back to the default model when no
// `summarize` route is configured), sizes the raw-segment input budget
// off the resolved checkpoint window (× the overshoot factor), renders
// the focus prompt, and streams the brief. The model layer owns the
// call deadline (route batch-deadlines + the turn ctx), so no extra
// timeout is wrapped here. Returns an error (no router / no renderer /
// empty segment / LLM failure) so the caller can fall back gracefully.
func (e *Extension) SummarizeSegment(ctx context.Context, state extension.SessionState, entries []HistoryEntry, agentNote string) (string, error) {
	if e.deps.Router == nil {
		return "", fmt.Errorf("hide summary: no model router")
	}
	if e.deps.Prompts == nil {
		return "", fmt.Errorf("hide summary: no prompts renderer")
	}
	if len(entries) == 0 {
		return "", fmt.Errorf("hide summary: empty segment")
	}
	renderer := e.deps.Prompts

	// Input budget tracks the checkpoint window (× overshoot factor),
	// not a hardcoded figure — a small window means small segments and a
	// small brief input; a large window scales it up. The summary
	// model's context window must cover this.
	cfg := e.resolveTierConfig(ctx, state)
	window := cfg.CheckpointWindowTokens
	if window <= 0 {
		window = defaultCheckpointWindowTokens
	}
	budgetTokens := window * hideBriefWindowFactorNum / hideBriefWindowFactorDen
	budgetChars := budgetTokens * 4 // 4-char/token heuristic, matches estimateTokens

	mdl, _, err := e.deps.Router.Resolve(ctx, model.Hint{Intent: model.IntentSummarize})
	if err != nil {
		return "", fmt.Errorf("hide summary: resolve model: %w", err)
	}
	body, err := renderer.Render("compactor/hide_brief", hideBriefInput{
		AgentNote: strings.TrimSpace(agentNote),
		RawLog:    flattenEntriesForBrief(entries, budgetChars),
		MaxTokens: hideBriefMaxTokens,
	})
	if err != nil {
		return "", fmt.Errorf("hide summary: render: %w", err)
	}
	return extension.StreamModelText(ctx, mdl, body, hideBriefMaxTokens)
}

// flattenEntriesForBrief renders the segment entries to a compact
// labelled log for the summariser, clipping each entry. If the whole
// log exceeds maxChars it keeps the HEAD and the TAIL (60/40) with a
// middle marker — instructions/contracts cluster at the start (a file
// read) and recent results at the end, so head+tail loses less than a
// plain head cut.
func flattenEntriesForBrief(entries []HistoryEntry, maxChars int) string {
	var b strings.Builder
	for _, e := range entries {
		m := e.Message
		switch m.Role {
		case model.RoleUser:
			b.WriteString("[input] ")
			b.WriteString(clipBrief(m.Content, hideBriefEntryMaxChars))
			b.WriteByte('\n')
		case model.RoleAssistant:
			if c := strings.TrimSpace(m.Content); c != "" {
				b.WriteString("[agent] ")
				b.WriteString(clipBrief(c, hideBriefEntryMaxChars))
				b.WriteByte('\n')
			}
			for _, tc := range m.ToolCalls {
				b.WriteString("[tool_call] ")
				b.WriteString(tc.Name)
				b.WriteByte(' ')
				b.WriteString(clipBrief(argsToBriefString(tc.Args), 400))
				b.WriteByte('\n')
			}
		case model.RoleTool:
			b.WriteString("[tool_result] ")
			b.WriteString(clipBrief(m.Content, hideBriefEntryMaxChars))
			b.WriteByte('\n')
		}
	}
	return headTailClip(b.String(), maxChars)
}

// headTailClip keeps the first 60% and last 40% of s when it exceeds
// maxChars, joined by a truncation marker. Returns s unchanged when it
// fits.
func headTailClip(s string, maxChars int) string {
	if len(s) <= maxChars {
		return s
	}
	head := maxChars * 6 / 10
	tail := maxChars - head
	return s[:head] + "\n…[middle of segment truncated]…\n" + s[len(s)-tail:]
}

func clipBrief(s string, n int) string {
	if len(s) > n {
		return s[:n] + "…"
	}
	return s
}

func argsToBriefString(v any) string {
	if v == nil {
		return ""
	}
	if s, ok := v.(string); ok {
		return s
	}
	b, err := json.Marshal(v)
	if err != nil {
		return ""
	}
	return string(b)
}
