-- Memory Storage Schema (Go template)
--
-- Template params:
--   .VectorSize       int    — embedding dimension (0 = no embeddings)
--   .EmbedderModel    string — hugr data source name for embedder ("" = disabled)
--   .IsTimescale      bool   — true if PostgreSQL with TimescaleDB extension
--
-- Template functions (from query-engine/pkg/db/sql_template.go):
--   isPostgres()  — true if PostgreSQL backend
--   isDuckDB()    — true if DuckDB backend
--
-- Executed on a DIRECT connection to the DB file (not via ATTACH).
-- No catalog qualification needed — all names resolve against the main
-- catalog of the connection.
--
-- APPEND-ONLY: no UPDATE on memory_items / hypotheses.
-- All mutations = INSERT + soft delete (SET deleted_at) for agent_types/agents only.
-- IDs generated by Go (synthetic sortable format: prefix_agent_ts_random).

{{ if isDuckDB }}
INSTALL json; LOAD json;
{{ if gt .VectorSize 0 }}INSTALL vss; LOAD vss;{{ end }}
{{ end }}

{{ if isPostgres }}
{{ if gt .VectorSize 0 }}CREATE EXTENSION IF NOT EXISTS vector;{{ end }}
{{ if .IsTimescale }}CREATE EXTENSION IF NOT EXISTS timescaledb;{{ end }}
{{ end }}

-- ============================================================
-- Version tracking — for migration system
-- ============================================================

CREATE TABLE IF NOT EXISTS version (
    name        VARCHAR PRIMARY KEY,
    version     VARCHAR NOT NULL,
    updated_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
);

-- ============================================================
-- Agent types — configuration templates for agent instances.
-- ============================================================

CREATE TABLE IF NOT EXISTS agent_types (
    id              VARCHAR PRIMARY KEY,
    name            VARCHAR NOT NULL,
    description     VARCHAR,
    config          {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    updated_at      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    deleted_at      {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
);

-- ============================================================
-- Agents — running instances of an agent type.
-- ============================================================

CREATE TABLE IF NOT EXISTS agents (
    id              VARCHAR PRIMARY KEY,
    agent_type_id   VARCHAR NOT NULL,
    short_id        VARCHAR NOT NULL,
    name            VARCHAR NOT NULL,
    status          VARCHAR DEFAULT 'active',
    config_override {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    last_active     {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    deleted_at      {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
);

-- ============================================================
-- Memory items (facts)
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_items (
    id          VARCHAR   PRIMARY KEY,
    agent_id    VARCHAR   NOT NULL,
    content     VARCHAR   NOT NULL,
    category    VARCHAR   NOT NULL,
    volatility  VARCHAR   DEFAULT 'stable',
    score       {{ if isPostgres }}DOUBLE PRECISION{{ else }}DOUBLE{{ end }} DEFAULT 0.5,
    source      VARCHAR,
    valid_from  {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }} NOT NULL,
    valid_to    {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }} NOT NULL,
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
    {{ if gt .VectorSize 0 }},embedding  {{ if isPostgres }}vector({{ .VectorSize }}){{ else }}FLOAT[{{ .VectorSize }}]{{ end }}{{ end }}
);

-- ============================================================
-- Memory log — audit trail for all memory operations.
-- Event types: retrieve, store, reinforce, supersede, delete,
--              add_tag, remove_tag, add_link, remove_link
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_log (
    event_time      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    event_type      VARCHAR   NOT NULL,
    memory_item_id  VARCHAR   NOT NULL,
    session_id      VARCHAR,
    agent_id        VARCHAR   NOT NULL,
    details         {{ if isPostgres }}JSONB{{ else }}JSON{{ end }}
);

{{ if .IsTimescale }}
SELECT create_hypertable('memory_log', 'event_time', if_not_exists => TRUE);
{{ end }}

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_memlog_item  ON memory_log (memory_item_id, event_type);
CREATE INDEX IF NOT EXISTS idx_memlog_agent ON memory_log (agent_id, event_time);
{{ end }}

{{ if gt .VectorSize 0 }}
{{ if isPostgres }}CREATE INDEX IF NOT EXISTS memory_vss ON memory_items USING hnsw (embedding vector_cosine_ops);{{ end }}
{{ end }}

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_mem_agent_category ON memory_items (agent_id, category);
CREATE INDEX IF NOT EXISTS idx_mem_agent_valid    ON memory_items (agent_id, valid_to);
CREATE INDEX IF NOT EXISTS idx_mem_score          ON memory_items (score DESC);
{{ end }}

-- ============================================================
-- Memory tags — one tag per row per memory item.
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_tags (
    memory_item_id  VARCHAR NOT NULL,
    tag             VARCHAR NOT NULL
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_tags_item ON memory_tags (memory_item_id);
CREATE INDEX IF NOT EXISTS idx_tags_tag  ON memory_tags (tag);
{{ end }}

-- ============================================================
-- Memory links — directed edges between facts.
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_links (
    source_id   VARCHAR NOT NULL,
    target_id   VARCHAR NOT NULL,
    relation    VARCHAR,
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    valid_to    {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_links_source ON memory_links (source_id);
CREATE INDEX IF NOT EXISTS idx_links_target ON memory_links (target_id);
{{ end }}

-- ============================================================
-- Hypotheses
-- ============================================================

CREATE TABLE IF NOT EXISTS hypotheses (
    id              VARCHAR   PRIMARY KEY,
    agent_id        VARCHAR   NOT NULL,
    content         VARCHAR   NOT NULL,
    category        VARCHAR,
    status          VARCHAR   DEFAULT 'proposed',
    priority        VARCHAR   DEFAULT 'medium',
    verification    VARCHAR,
    estimated_calls INTEGER   DEFAULT 3,
    source_session  VARCHAR,
    created_at      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    checked_at      {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }},
    result          VARCHAR,
    fact_id         VARCHAR
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_hyp_agent_status ON hypotheses (agent_id, status, priority);
{{ end }}

-- ============================================================
-- Sessions — agent conversation sessions.
-- ============================================================

CREATE TABLE IF NOT EXISTS sessions (
    id                    VARCHAR   PRIMARY KEY,
    agent_id              VARCHAR   NOT NULL,
    owner_id              VARCHAR,
    parent_session_id     VARCHAR,
    fork_after_seq        INTEGER,
    -- spec 006 (schema 0.0.2): explicit discriminator. 'root' = user
    -- conversation, 'subagent' = agent-spawned specialist (own context),
    -- 'fork' = reserved for future user-initiated fork.
    session_type          VARCHAR   NOT NULL DEFAULT 'root',
    -- spec 006: FK to the session_events row on the parent session that
    -- spawned this child (non-empty only when session_type = 'subagent').
    spawned_from_event_id VARCHAR,
    status                VARCHAR   DEFAULT 'active',
    mission               VARCHAR,
    metadata              {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at            {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    updated_at            {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_sessions_agent  ON sessions (agent_id, status);
CREATE INDEX IF NOT EXISTS idx_sessions_parent ON sessions (parent_session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_type   ON sessions (agent_id, session_type);
{{ end }}

-- ============================================================
-- Session participants — multi-user sessions.
-- ============================================================

CREATE TABLE IF NOT EXISTS session_participants (
    session_id  VARCHAR   NOT NULL,
    user_id     VARCHAR   NOT NULL,
    role        VARCHAR   DEFAULT 'participant',
    joined_at   {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    left_at     {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_participants_session ON session_participants (session_id);
CREATE INDEX IF NOT EXISTS idx_participants_user    ON session_participants (user_id);
{{ end }}

-- ============================================================
-- Session events — full conversation transcript.
-- ============================================================

CREATE TABLE IF NOT EXISTS session_events (
    id          VARCHAR   {{ if not .IsTimescale }}PRIMARY KEY{{ end }},
    session_id  VARCHAR   NOT NULL,
    agent_id    VARCHAR   NOT NULL,
    seq         INTEGER   NOT NULL,
    event_type  VARCHAR   NOT NULL,
    author      VARCHAR   NOT NULL,
    content     VARCHAR,
    tool_name   VARCHAR,
    tool_args   {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    tool_result VARCHAR,
    metadata    {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
    -- spec 006 (schema 0.0.2): semantic embedding of content for semantic
    -- search. NULL for lifecycle events / oversize / transient embedder
    -- failures. Populated server-side via Hugr's `summary:` mutation
    -- parameter on insert (see pkg/sessions/classifier.go).
    {{ if gt .VectorSize 0 }}
    ,embedding  {{ if isPostgres }}vector({{ .VectorSize }}){{ else }}FLOAT[{{ .VectorSize }}]{{ end }}
    {{ end }}
    {{ if .IsTimescale }}, PRIMARY KEY (created_at, id){{ end }}
);

{{ if .IsTimescale }}
SELECT create_hypertable('session_events', 'created_at', if_not_exists => TRUE);
{{ end }}

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_events_session ON session_events (session_id, seq);
CREATE INDEX IF NOT EXISTS idx_events_type    ON session_events (session_id, event_type);
{{ end }}

{{ if gt .VectorSize 0 }}
{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS session_events_vss
    ON session_events USING hnsw (embedding vector_cosine_ops);
{{ end }}
-- DuckDB HNSW on persistent files needs hnsw_enable_experimental_persistence
-- = true. We follow the existing convention from memory_items and skip the
-- index on DuckDB; sequential vector scan is acceptable at single-agent scale
-- and the engine can be upgraded later by toggling the pragma at startup.
{{ end }}

-- ============================================================
-- Session notes
-- ============================================================

CREATE TABLE IF NOT EXISTS session_notes (
    id                VARCHAR   PRIMARY KEY,
    agent_id          VARCHAR   NOT NULL,
    -- Phase 4.2.3 — session_id is always the ROOT of the writing
    -- session's parent chain. The notepad extension climbs
    -- RootAncestor() before AppendNote so every session in the tree
    -- sees the same notepad. session_notes_chain view preserves the
    -- legacy parent-walk surface for observability.
    session_id        VARCHAR   NOT NULL,
    -- Session that actually wrote the note. May differ from
    -- session_id when a sub-agent's notepad:append climbs to root
    -- for storage. Audit trail only — never used for visibility.
    author_session_id VARCHAR,
    -- Phase 4.2.3 — open-string filtering tag, model-supplied at
    -- notepad:append time; skills may advertise recommended values.
    category          VARCHAR,
    -- Tier of authoring session at write time: agent | coordinator
    -- | worker. Set by runtime from author's tier.
    author_role       VARCHAR,
    -- Model-supplied short context phrase — what the writing
    -- session thinks it is working on. Optional.
    mission           VARCHAR,
    content           VARCHAR   NOT NULL,
    created_at        {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
    {{ if gt .VectorSize 0 }}
    ,embedding        {{ if isPostgres }}vector({{ .VectorSize }}){{ else }}FLOAT[{{ .VectorSize }}]{{ end }}
    {{ end }}
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_notes_agent_session ON session_notes (agent_id, session_id);
CREATE INDEX IF NOT EXISTS idx_notes_author        ON session_notes (agent_id, author_session_id);
{{ end }}

-- ============================================================
-- Session reviews
-- ============================================================

CREATE TABLE IF NOT EXISTS session_reviews (
    id               VARCHAR   PRIMARY KEY,
    agent_id         VARCHAR   NOT NULL,
    session_id       VARCHAR   NOT NULL,
    status           VARCHAR   DEFAULT 'pending',
    facts_stored     INTEGER   DEFAULT 0,
    facts_reinforced INTEGER   DEFAULT 0,
    hypotheses_added INTEGER   DEFAULT 0,
    model_used       VARCHAR,
    tokens_used      INTEGER   DEFAULT 0,
    reviewed_at      {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }},
    error            VARCHAR
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_reviews_agent ON session_reviews (agent_id, session_id);
{{ end }}

-- ============================================================
-- Artifacts registry (spec 008 / migration 0.0.3 — additive)
--   Bytes live OUTSIDE hub.db in the active Storage backend
--   (filesystem on phase 3; S3 stub registered but unused).
--   Manager resolves them via Storage.Open(ObjectRef{Backend, Key}).
--   Indexes are POSTGRES-ONLY — DuckDB stays index-free for these
--   tables (per project rule + sparse cardinality assumption).
-- ============================================================

CREATE TABLE IF NOT EXISTS artifacts (
    id              VARCHAR PRIMARY KEY,
    agent_id        VARCHAR NOT NULL,
    name            VARCHAR NOT NULL,
    type            VARCHAR NOT NULL,
    storage_key     VARCHAR NOT NULL,
    storage_backend VARCHAR NOT NULL,
    original_path   VARCHAR,
    description     VARCHAR NOT NULL,
    {{ if gt .VectorSize 0 }}description_embedding {{ if isPostgres }}vector({{ .VectorSize }}){{ else }}FLOAT[{{ .VectorSize }}]{{ end }},{{ end }}
    session_id          VARCHAR NOT NULL,
    mission_session_id  VARCHAR,
    derived_from        VARCHAR,
    visibility          VARCHAR NOT NULL DEFAULT 'self',
    created_at          {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    size_bytes          BIGINT,
    row_count           BIGINT,
    col_count           INTEGER,
    file_schema         {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    tags                VARCHAR[],
    ttl                 VARCHAR NOT NULL DEFAULT 'session'
);

CREATE TABLE IF NOT EXISTS artifact_grants (
    artifact_id  VARCHAR NOT NULL,
    agent_id     VARCHAR NOT NULL,
    session_id   VARCHAR NOT NULL,
    granted_by   VARCHAR NOT NULL,
    granted_at   {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    PRIMARY KEY (artifact_id, agent_id, session_id)
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_art_agent
    ON artifacts (agent_id);
CREATE INDEX IF NOT EXISTS idx_art_session
    ON artifacts (agent_id, session_id);
CREATE INDEX IF NOT EXISTS idx_art_mission
    ON artifacts (mission_session_id) WHERE mission_session_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_art_ttl
    ON artifacts (ttl, created_at) WHERE ttl <> 'permanent';
CREATE INDEX IF NOT EXISTS idx_art_grants_target
    ON artifact_grants (agent_id, session_id);
{{ if gt .VectorSize 0 }}
CREATE INDEX IF NOT EXISTS artifacts_desc_vss
    ON artifacts USING hnsw (description_embedding vector_cosine_ops);
{{ end }}
{{ end }}

-- ============================================================
-- HITL Approvals + Tool Policies (spec 009 / phase 4)
--   See pkg/store/local/migrate/migrations/0.0.5/ for upgrade
--   migrations against existing 0.0.3 deployments.
--   Indexes are POSTGRES-ONLY — DuckDB stays index-free.
-- ============================================================

CREATE TABLE IF NOT EXISTS approvals (
    id                  VARCHAR PRIMARY KEY,
    agent_id            VARCHAR NOT NULL,
    mission_session_id  VARCHAR NOT NULL,
    coord_session_id    VARCHAR NOT NULL,
    tool_name           VARCHAR NOT NULL,
    args                {{ if isPostgres }}JSONB{{ else }}JSON{{ end }} NOT NULL,
    risk                VARCHAR NOT NULL,
    status              VARCHAR NOT NULL,
    response            {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at          {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL,
    responded_at        {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
);

CREATE TABLE IF NOT EXISTS tool_policies (
    agent_id    VARCHAR NOT NULL,
    tool_name   VARCHAR NOT NULL,
    scope       VARCHAR NOT NULL,
    policy      VARCHAR NOT NULL,
    note        VARCHAR,
    created_by  VARCHAR NOT NULL,
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL,
    updated_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL,
    PRIMARY KEY (agent_id, tool_name, scope)
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_approvals_coord
    ON approvals (agent_id, coord_session_id, status);
CREATE INDEX IF NOT EXISTS idx_policies_agent_scope
    ON tool_policies (agent_id, scope);
{{ end }}
