-- Agent Storage Schema (Go template)
--
-- Template params (query-engine common convention — hugrapp.TemplateParams):
--   .VectorSize   int    — embedding dimension (0 = no embeddings)
--   .EmbedderName string — hugr data source name for the embedder (SDL only)
--
-- Template functions (from query-engine/pkg/db/sql_template.go):
--   isPostgres()  — PostgreSQL backend (⟹ TimescaleDB hypertables + pgvector)
--   isDuckDB()    — DuckDB backend
--
-- Executed on a DIRECT connection to the DB file (not via ATTACH).
-- No catalog qualification needed — all names resolve against the main
-- catalog of the connection.
--
-- APPEND-ONLY on the log tables (session_events / skill_log / task_log):
-- no UPDATE. Mutations = INSERT + soft delete (SET deleted_at) for
-- agent_types/agents only. IDs generated by Go (synthetic sortable
-- format: prefix_agent_ts_random).

{{ if isDuckDB }}
INSTALL json; LOAD json;
{{ if gt .VectorSize 0 }}INSTALL vss; LOAD vss;{{ end }}
{{ end }}

{{ if isPostgres }}
{{ if gt .VectorSize 0 }}CREATE EXTENSION IF NOT EXISTS vector;{{ end }}
{{ if isPostgres }}CREATE EXTENSION IF NOT EXISTS timescaledb;{{ end }}
{{ end }}

-- ============================================================
-- Version tracking — for migration system
-- ============================================================

CREATE TABLE IF NOT EXISTS version (
    name        VARCHAR PRIMARY KEY,
    version     VARCHAR NOT NULL,
    updated_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
);

-- ============================================================
-- Agent types — configuration templates for agent instances.
-- ============================================================

CREATE TABLE IF NOT EXISTS agent_types (
    id              VARCHAR PRIMARY KEY,
    name            VARCHAR NOT NULL,
    description     VARCHAR,
    config          {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    updated_at      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    deleted_at      {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
);

-- ============================================================
-- Agents — running instances of an agent type.
-- ============================================================

CREATE TABLE IF NOT EXISTS agents (
    id              VARCHAR PRIMARY KEY,
    agent_type_id   VARCHAR NOT NULL,
    short_id        VARCHAR NOT NULL,
    name            VARCHAR NOT NULL,
    status          VARCHAR DEFAULT 'active',
    -- Hugr auth role stamped into the agent's JWT by the hub token issuer
    -- (spec-hub-side §1.3, D10): admin-assigned at agent creation, e.g.
    -- 'agent' (default, RLS-scoped) | 'agent_template' | an admin role.
    role            VARCHAR DEFAULT 'agent',
    config_override {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at      {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    last_active     {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    deleted_at      {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
);

-- ============================================================
-- Sessions — agent conversation sessions.
-- ============================================================

CREATE TABLE IF NOT EXISTS sessions (
    id                    VARCHAR   PRIMARY KEY,
    agent_id              VARCHAR   NOT NULL,
    owner_id              VARCHAR,
    parent_session_id     VARCHAR,
    fork_after_seq        INTEGER,
    -- spec 006 (schema 0.0.2): explicit discriminator. 'root' = user
    -- conversation, 'subagent' = agent-spawned specialist (own context),
    -- 'fork' = reserved for future user-initiated fork.
    session_type          VARCHAR   NOT NULL DEFAULT 'root',
    -- spec 006: FK to the session_events row on the parent session that
    -- spawned this child (non-empty only when session_type = 'subagent').
    spawned_from_event_id VARCHAR,
    status                VARCHAR   DEFAULT 'active',
    mission               VARCHAR,
    metadata              {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at            {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }},
    updated_at            {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_sessions_agent  ON sessions (agent_id, status);
CREATE INDEX IF NOT EXISTS idx_sessions_parent ON sessions (parent_session_id);
CREATE INDEX IF NOT EXISTS idx_sessions_type   ON sessions (agent_id, session_type);
{{ end }}

-- ============================================================
-- Session events — full conversation transcript.
-- ============================================================

CREATE TABLE IF NOT EXISTS session_events (
    id          VARCHAR   {{ if not (isPostgres) }}PRIMARY KEY{{ end }},
    session_id  VARCHAR   NOT NULL,
    agent_id    VARCHAR   NOT NULL,
    seq         INTEGER   NOT NULL,
    event_type  VARCHAR   NOT NULL,
    author      VARCHAR   NOT NULL,
    content     VARCHAR,
    tool_name   VARCHAR,
    tool_args   {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    tool_result VARCHAR,
    metadata    {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
    -- spec 006 (schema 0.0.2): semantic embedding of content for semantic
    -- search. NULL for lifecycle events / oversize / transient embedder
    -- failures. Populated server-side via Hugr's `summary:` mutation
    -- parameter on insert (see pkg/sessions/classifier.go).
    {{ if gt .VectorSize 0 }}
    ,embedding  {{ if isPostgres }}vector({{ .VectorSize }}){{ else }}FLOAT[{{ .VectorSize }}]{{ end }}
    {{ end }}
    {{ if isPostgres }}, PRIMARY KEY (created_at, id){{ end }}
);

{{ if isPostgres }}
SELECT create_hypertable('session_events', 'created_at', if_not_exists => TRUE);
{{ end }}

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_events_session ON session_events (session_id, seq);
CREATE INDEX IF NOT EXISTS idx_events_type    ON session_events (session_id, event_type);
{{ end }}

{{ if gt .VectorSize 0 }}
{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS session_events_vss
    ON session_events USING hnsw (embedding vector_cosine_ops);
{{ end }}
-- DuckDB HNSW on persistent files needs hnsw_enable_experimental_persistence
-- = true. We follow the existing convention and skip the index on DuckDB;
-- sequential vector scan is acceptable at single-agent scale and the engine
-- can be upgraded later by toggling the pragma at startup.
{{ end }}

-- ============================================================
-- Session notes
-- ============================================================

CREATE TABLE IF NOT EXISTS session_notes (
    id                VARCHAR   PRIMARY KEY,
    agent_id          VARCHAR   NOT NULL,
    -- Phase 4.2.3 — session_id is always the ROOT of the writing
    -- session's parent chain. The notepad extension climbs
    -- RootAncestor() before AppendNote so every session in the tree
    -- sees the same notepad.
    session_id        VARCHAR   NOT NULL,
    -- Session that actually wrote the note. May differ from
    -- session_id when a sub-agent's notepad:append climbs to root
    -- for storage. Audit trail only — never used for visibility.
    author_session_id VARCHAR,
    -- Phase 4.2.3 — open-string filtering tag, model-supplied at
    -- notepad:append time; skills may advertise recommended values.
    category          VARCHAR,
    -- Tier of authoring session at write time: agent | coordinator
    -- | worker. Set by runtime from author's tier.
    author_role       VARCHAR,
    -- Model-supplied short context phrase — what the writing
    -- session thinks it is working on. Optional.
    mission           VARCHAR,
    content           VARCHAR   NOT NULL,
    created_at        {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }}
    {{ if gt .VectorSize 0 }}
    ,embedding        {{ if isPostgres }}vector({{ .VectorSize }}){{ else }}FLOAT[{{ .VectorSize }}]{{ end }}
    {{ end }}
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_notes_agent_session ON session_notes (agent_id, session_id);
CREATE INDEX IF NOT EXISTS idx_notes_author        ON session_notes (agent_id, author_session_id);
{{ end }}

-- ============================================================
-- Tool Policies (spec 009 / phase 4)
--   Indexes are POSTGRES-ONLY — DuckDB stays index-free.
-- ============================================================

CREATE TABLE IF NOT EXISTS tool_policies (
    agent_id    VARCHAR NOT NULL,
    tool_name   VARCHAR NOT NULL,
    scope       VARCHAR NOT NULL,
    policy      VARCHAR NOT NULL,
    note        VARCHAR,
    created_by  VARCHAR NOT NULL,
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL,
    updated_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL,
    PRIMARY KEY (agent_id, tool_name, scope)
);

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_policies_agent_scope
    ON tool_policies (agent_id, scope);
{{ end }}

-- ============================================================
-- Tasks + task_log (Phase 6 / migration 0.0.6) — user-defined
-- schedule entries + append-only fire event log.
--
-- `tasks` UPDATEs are bounded by operator actions (pause /
-- resume / cancel / spec edit). `task_log` is pure INSERT — no
-- UPDATE column, no finalisation patch. Schedule anchor lives
-- in the latest `planned` row (denormalised fire_seq + planned_at
-- on every entry). See phase-6-spec.md §2.7 for the
-- update-minimisation contract.
-- ============================================================

-- Phase 6 / 0.0.7 deliberately stores task timestamps in TIMESTAMPTZ
-- on BOTH backends (DuckDB included). Existing tables use a naive
-- TIMESTAMP on DuckDB for legacy reasons; tasks need correct TZ
-- handling because Runner reads `planned_at` and compares it against
-- the wall clock for the due check — a silent UTC -> local drift
-- inside DuckDB would push the schedule off by the local offset.
-- DuckDB's TIMESTAMPTZ is fully wire-compatible with Postgres'
-- timestamptz; same Hugr scan path on both.

CREATE TABLE IF NOT EXISTS tasks (
    id                VARCHAR PRIMARY KEY,
    agent_id          VARCHAR NOT NULL,
    kind              VARCHAR NOT NULL,
    status            VARCHAR NOT NULL DEFAULT 'active',
    schedule_kind     VARCHAR NOT NULL,
    owner_session_id  VARCHAR NOT NULL,
    skill_ref         VARCHAR,
    spec              {{ if isPostgres }}JSONB{{ else }}JSON{{ end }} NOT NULL,
    pause_reason      VARCHAR,
    created_at        TIMESTAMPTZ DEFAULT {{ if isPostgres }}NOW(){{ else }}CURRENT_TIMESTAMP{{ end }} NOT NULL,
    updated_at        TIMESTAMPTZ DEFAULT {{ if isPostgres }}NOW(){{ else }}CURRENT_TIMESTAMP{{ end }} NOT NULL
);

CREATE TABLE IF NOT EXISTS task_log (
    id          VARCHAR   {{ if not (isPostgres) }}PRIMARY KEY{{ end }},
    task_id     VARCHAR   NOT NULL,
    agent_id    VARCHAR   NOT NULL,
    fire_seq    INTEGER   NOT NULL,
    event_type  VARCHAR   NOT NULL,
    planned_at  TIMESTAMPTZ NOT NULL,
    session_id  VARCHAR,
    outcome     {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    content     VARCHAR,
    created_at  TIMESTAMPTZ DEFAULT {{ if isPostgres }}NOW(){{ else }}CURRENT_TIMESTAMP{{ end }} NOT NULL
    {{ if isPostgres }}, PRIMARY KEY (created_at, id){{ end }}
);

{{ if isPostgres }}
SELECT create_hypertable('task_log', 'created_at', if_not_exists => TRUE);
{{ end }}

{{ if isPostgres }}
-- Tasks: lifecycle + ownership lookups. Partial index on active
-- rows keeps the Runner's ListDue scan cheap when most tasks are
-- paused / cancelled.
CREATE INDEX IF NOT EXISTS idx_tasks_active
    ON tasks (agent_id, status) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_tasks_owner
    ON tasks (agent_id, owner_session_id);

-- Task log: every read is keyed by (task_id, event_type, fire_seq
-- DESC). Single composite index covers `next planned` +
-- `last successful` + `latest of any event_type per fire`.
CREATE INDEX IF NOT EXISTS idx_task_log_latest
    ON task_log (task_id, event_type, fire_seq DESC, created_at DESC);

-- In-flight scan (reaper): started rows older than cutoff.
CREATE INDEX IF NOT EXISTS idx_task_log_started
    ON task_log (agent_id, created_at)
    WHERE event_type = 'started';
{{ end }}

-- ============================================================
-- Dynamic skills (Phase 6.2.db / migration 0.0.8) — DB-backed
-- skill source: on-disk bundle + DB index for semantic discovery,
-- usage ranking, and package management.
--
--   • skills      — one index row per dynamic-skill bundle. The
--                   `metadata` JSON carries the full metadata.hugen
--                   projection so mission roles / task inputs_schema
--                   are served WITHOUT a SKILL.md read; the filter
--                   columns (type / task_eligible / task_kind /
--                   keywords / tier_compat / has_inputs_schema) are
--                   denormalised from it for cheap WHERE. `source`
--                   is the reapability/provenance anchor; `pin`
--                   bypasses the discovery bandit. UPDATEs bounded
--                   by install / update-at-start / config-set.
--   • skill_log   — append-only usage telemetry {shown,loaded,used}.
--                   No mutable counters on the hot path; bandit
--                   counts roll up off-line (db-2).
--   • skill_links — m2m edges between skills (catalog_member /
--                   autoload / requires / related). A plain junction
--                   with two FKs to skills.id, no parent_id self-FK
--                   on skills.
--
-- `shared` is a forward-compat column (cross-agent visibility) —
-- the sharing LOGIC is deferred to db-3 (hub mode). Indexes are
-- POSTGRES-ONLY; DuckDB stays index-free per the existing rule.
-- ============================================================

CREATE TABLE IF NOT EXISTS skills (
    id                VARCHAR PRIMARY KEY,
    agent_id          VARCHAR NOT NULL,
    shared            BOOLEAN NOT NULL DEFAULT FALSE,
    name              VARCHAR NOT NULL,
    type              VARCHAR NOT NULL DEFAULT 'skill',
    description       VARCHAR,
    task_eligible     BOOLEAN NOT NULL DEFAULT FALSE,
    task_kind         VARCHAR,
    keywords          VARCHAR[],
    tier_compat       VARCHAR[],
    has_inputs_schema BOOLEAN NOT NULL DEFAULT FALSE,
    metadata          {{ if isPostgres }}JSONB{{ else }}JSON{{ end }} NOT NULL,
    pin               BOOLEAN NOT NULL DEFAULT FALSE,
    source            VARCHAR NOT NULL,
    version           VARCHAR,
    content_hash      VARCHAR,
    bundle_path       VARCHAR,
    owner             VARCHAR,
    created_at        {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL,
    updated_at        {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL,
    installed_at      {{ if isPostgres }}TIMESTAMPTZ{{ else }}TIMESTAMP{{ end }}
    {{ if gt .VectorSize 0 }},description_vec {{ if isPostgres }}vector({{ .VectorSize }}){{ else }}FLOAT[{{ .VectorSize }}]{{ end }}{{ end }}
);

CREATE TABLE IF NOT EXISTS skill_log (
    id          VARCHAR PRIMARY KEY,
    skill_id    VARCHAR NOT NULL,
    agent_id    VARCHAR NOT NULL,
    event       VARCHAR NOT NULL,
    session_id  VARCHAR,
    details     {{ if isPostgres }}JSONB{{ else }}JSON{{ end }},
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL
);

CREATE TABLE IF NOT EXISTS skill_links (
    agent_id    VARCHAR NOT NULL,
    source_id   VARCHAR NOT NULL,
    target_id   VARCHAR NOT NULL,
    relation    VARCHAR NOT NULL,
    created_at  {{ if isPostgres }}TIMESTAMPTZ DEFAULT NOW(){{ else }}TIMESTAMP DEFAULT CURRENT_TIMESTAMP{{ end }} NOT NULL
);

{{ if gt .VectorSize 0 }}
{{ if isPostgres }}CREATE INDEX IF NOT EXISTS skills_desc_vss ON skills USING hnsw (description_vec vector_cosine_ops);{{ end }}
{{ end }}

{{ if isPostgres }}
CREATE INDEX IF NOT EXISTS idx_skills_agent       ON skills (agent_id, type);
-- (agent_id, source, name) is the upsert identity tuple — UNIQUE so a
-- TOCTOU double-insert (concurrent reconcile / publish racing the
-- lookup) fails loud instead of silently duplicating.
CREATE UNIQUE INDEX IF NOT EXISTS uq_skills_agent_source_name ON skills (agent_id, source, name);
CREATE INDEX IF NOT EXISTS idx_skills_task        ON skills (agent_id, task_eligible);
CREATE INDEX IF NOT EXISTS idx_skill_log_skill    ON skill_log (skill_id, event);
CREATE INDEX IF NOT EXISTS idx_skill_log_agent    ON skill_log (agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_skill_links_source ON skill_links (agent_id, source_id, relation);
CREATE INDEX IF NOT EXISTS idx_skill_links_target ON skill_links (agent_id, target_id, relation);
{{ end }}
